trigger:
- master

jobs:
- job: Mac
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - checkout: self
    clean: true
    submodules: true
  - script: scripts/BuildMac
    displayName: 'macOS Build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'macOS'
      targetPath: 'Development/Deploy'
